server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
logging:
    level: ERROR
#     logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    canada-metadata:
        type: collection
        title:
            en: Open Canada sample data
            fr: Exemple de donn\u00e9es Canada Ouvert
        description:
            en: Sample metadata records from open.canada.ca
            fr: Exemples d'enregistrements de m\u00e9tadonn\u00e9es sur ouvert.canada.ca
        keywords:
            en:
                - canada
                - open data
            fr:
                - canada
                - donn\u00e9es ouvertes
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://open.canada.ca/en/open-data
              hreflang: en-CA
            - type: text/html
              rel: alternate
              title: informations
              href: https://ouvert.canada.ca/fr/donnees-ouvertes
              hreflang: fr-CA
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: TinyDBCatalogue
              data: tests/data/open.canada.ca/sample-records.tinydb
              id_field: externalId
              time_field: created
              title_field: title

    rise-edr:
        type: collection
        title: rise edr
        description: rise is a usbr api
        keywords:
            - open data
        extents:
            spatial:
                bbox: [-171.791110603, 18.91619, -66.96466, 71.3577635769]

                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: edr
              name: rise.rise_edr.RiseEDRProvider
              data: https://data.usbr.gov/
              cache: redis
            - type: feature
              name: rise.rise.RiseProvider
              data: https://data.usbr.gov/
              entity: Observation
              title_field: name
              cache: redis

