server:
    admin: true 
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
logging:
    level: ERROR
#     logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
        description:
            en: pygeoapi provides an API to geospatial data
        keywords:
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Center for Geospatial Solutions
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    rise-edr:
        type: collection
        title: rise edr
        description: rise is a usbr api
        keywords:
            - open data
        extents:
            spatial:
                bbox: [-171.791110603, 18.91619, -66.96466, 71.3577635769]

                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
        # we define two providers here since in pygeoapi, the EDR provider needs a OAF provider
        # for the items endpoint
            - type: edr
              name: rise.rise_edr.RiseEDRProvider
              data: https://data.usbr.gov/
              cache: redis
            - type: feature
              name: rise.rise.RiseProvider
              data: https://data.usbr.gov/
              entity: Observation
              title_field: name
              cache: redis

